### ISSUE TITLE
Набирайте текст на родном языке, используя клавиатуру Gboard

### ISSUE THREAD

**Issue by ImperatorKonstantin** [w3c/wcag3#59]
Я пользуюсь клавиатурой Gboard на этих языках: Русский (Россия) (Русский) и Английский (Австралия) (QWERTY). Скачать ее можно здесь: https://gboard.app.goo.gl/5r2E1

**Comment by patrickhlauke** [comment]
Can we please block this user at repo/organisation level. thank you...
